flows:
  - name: default
    language: android
    version: jdk8
    env:
      - MY_VERSION=111

    trigger:
      push:
        - develop
        - master
      pull_request: true

    steps:
      - name: Init
        plugin:
          name: android_init

      - name: Git Clone
        plugin:
          name: git
          
      - name: Android Cache
        plugin:
          name: android_cache
          inputs:
           - FLOW_ENABLE_CACHE=TRUE
           
      - name: Memory
        scripts:
         - export ANDROID_OPTS='-Xms4g -Xmx4g'
          
          
      - name: Build
        plugin:
          name: android_build
          inputs:
           - FLOW_ANDROID_GRADLE_TASK=release
      
      - name: fir upload
        enable: true
        failure: false
        plugin:
          name: fir_plugin
          inputs:
            - FIR_API_TOKEN=352c3d571fa37474841adaca000c60e3
            - FIR_CHANGELOG='test change log $FLOW_EVENT_NUMBER'
